"""
Agent Tools for ARIA ReAct agent.

Tools:
  - web_search
  - wikipedia_search
  - generate_podcast_script
  - summarize_content
  - format_podcast_structure
  - memory_read / memory_write
"""
from __future__ import annotations

import json
import os
from typing import Any, Optional

from langchain_core.tools import tool
from loguru import logger


# ──────────────────────────────────────────────
# 1. Web Search (DuckDuckGo — no API key needed)
# ──────────────────────────────────────────────

@tool
def web_search(query: str) -> str:
    """
    Search the web for current information about a topic.
    Use this when you need recent news, data, or facts not in your knowledge.
    Input: a search query string.
    Output: top search results as text.
    """
    try:
        from duckduckgo_search import DDGS
        results = []
        with DDGS() as ddgs:
            for r in ddgs.text(query, max_results=4):
                results.append(f"• {r['title']}\n  {r['body']}")
        if not results:
            return "No results found."
        return "\n\n".join(results[:4])
    except Exception as exc:
        logger.warning(f"web_search failed: {exc}")
        return f"Web search temporarily unavailable. Error: {exc}"


# ──────────────────────────────────────────────
# 2. Wikipedia Search
# ──────────────────────────────────────────────

@tool
def wikipedia_search(topic: str) -> str:
    """
    Search Wikipedia for background information on a topic.
    Use for established facts, history, definitions.
    Input: a topic or concept name.
    Output: Wikipedia summary text.
    """
    try:
        import wikipedia
        wikipedia.set_lang("en")
        try:
            summary = wikipedia.summary(topic, sentences=6, auto_suggest=True)
            return summary
        except wikipedia.DisambiguationError as e:
            # Try first option
            summary = wikipedia.summary(e.options[0], sentences=5)
            return f"(Disambiguation — showing '{e.options[0]}')\n\n{summary}"
    except Exception as exc:
        logger.warning(f"wikipedia_search failed: {exc}")
        return f"Wikipedia search unavailable: {exc}"


# ──────────────────────────────────────────────
# 3. Generate Podcast Script
# ──────────────────────────────────────────────

@tool
def generate_podcast_script(topic_and_context: str) -> str:
    """
    Generate a complete podcast script for a given topic.
    Input: JSON string with keys 'topic' and optionally 'context', 'duration_minutes', 'style'.
    Output: Fully formatted podcast script with intro, segments, outro.
    """
    try:
        data = json.loads(topic_and_context)
    except Exception:
        data = {"topic": topic_and_context}

    topic = data.get("topic", "unknown topic")
    duration = data.get("duration_minutes", 15)
    style = data.get("style", "conversational")
    context = data.get("context", "")

    script = f"""
# 🎙️ PODCAST SCRIPT: {topic.upper()}
**Duration:** ~{duration} minutes | **Style:** {style.capitalize()}

---

## 🎬 INTRO (60–90 sec)

**[MUSIC FADES IN — upbeat, curious]**

HOST (ARIA):
"Welcome back to *The Signal*, the show where we cut through the noise and get to what actually matters.
I'm ARIA, and today — we're talking about {topic}.
{"Context: " + context if context else ""}
Whether you're brand new to this or deep in it — by the end of today's episode, you'll see it differently. Let's go."

**[MUSIC FADES OUT]**

---

## 📌 SEGMENT 1 — WHAT IS IT? (3–4 min)

HOST:
"So first — let's set the table. What exactly are we talking about when we say {topic}?
A lot of people use the term loosely, but there's real substance here.
Think of it this way: [analogy or framing].
And what makes it fascinating is [angle 1]."

**[SHORT PAUSE — ambient sound]**

---

## 🔍 SEGMENT 2 — WHY IT MATTERS NOW (4–5 min)

HOST:
"Here's what's changed recently, and why now is the critical moment.
[Trend or data point 1].
[Trend or data point 2].
The people who understand {topic} deeply right now? They're going to have a serious advantage."

---

## 💡 SEGMENT 3 — THE REAL STORY / INSIGHT (4–5 min)

HOST:
"But here's the thing most people miss — [counterintuitive insight].
I've been looking at this from [angle], and what stood out was [finding].
Let me paint a picture for you: [story or example]."

---

## 🎯 OUTRO (60–90 sec)

**[MUSIC FADES BACK IN]**

HOST:
"That's a wrap on today's deep dive into {topic}.
If this resonated — share it with someone who'd find it valuable.
And if you want to go deeper, I'll link resources in the show notes.
Until next time — stay curious, stay signal.
I'm ARIA. See you next episode."

**[MUSIC SWELLS — END]**

---
*Script generated by ARIA Podcast Agent*
"""
    return script.strip()


# ──────────────────────────────────────────────
# 4. Summarize Content
# ──────────────────────────────────────────────

@tool
def summarize_content(text: str) -> str:
    """
    Summarize a long piece of text into key points.
    Use after web_search or wikipedia_search to distil information.
    Input: raw text content to summarize.
    Output: bullet-point summary of key facts.
    """
    if not text or len(text) < 100:
        return text

    # Split into sentences and pick key ones
    sentences = [s.strip() for s in text.replace("\n", " ").split(".") if len(s.strip()) > 40]
    top = sentences[:8]

    summary = "Key points:\n" + "\n".join(f"• {s}." for s in top)
    return summary


# ──────────────────────────────────────────────
# 5. Format Podcast Structure
# ──────────────────────────────────────────────

@tool
def format_podcast_structure(raw_content: str) -> str:
    """
    Take raw research or notes and format them into a podcast episode structure.
    Input: JSON string with 'title', 'key_points' (list), optional 'guests'.
    Output: Episode breakdown — segments, timing, talking points.
    """
    try:
        data = json.loads(raw_content)
    except Exception:
        data = {"title": "Episode", "key_points": [raw_content]}

    title = data.get("title", "Untitled Episode")
    points = data.get("key_points", [])
    guests = data.get("guests", [])
    episode_num = data.get("episode_number", "")

    guest_line = f"**Guests:** {', '.join(guests)}" if guests else ""
    ep_line = f"Episode #{episode_num} — " if episode_num else ""

    segments = "\n".join(
        f"  **Segment {i+1}** [{3+i*2}–{5+i*2} min] — {pt}"
        for i, pt in enumerate(points[:5])
    )

    return f"""
## 📋 EPISODE STRUCTURE
### {ep_line}{title}
{guest_line}

**Total Runtime:** ~{10 + len(points) * 3} minutes

### Segments:
{segments if segments else "  • Main discussion (10 min)"}

### Flow:
1. Cold Open / Hook (1 min)
2. Host Intro + Context (2 min)
3. Main Content Segments (above)
4. Listener Q&A / Reflection (2 min)
5. Outro + CTA (1 min)

### Producer Notes:
- Record in one sitting for energy consistency
- Add chapter markers at each segment
- Music beds: fade in/out at transitions
""".strip()


# ──────────────────────────────────────────────
# 6. Memory Read
# ──────────────────────────────────────────────

@tool
def memory_read(session_id: str) -> str:
    """
    Read the conversation history for the current session from memory.
    Use this to recall what was discussed earlier in the conversation.
    Input: session_id string.
    Output: recent conversation history as formatted text.
    """
    import asyncio
    from app.services.memory_service import get_session_history

    try:
        loop = asyncio.get_event_loop()
        history = loop.run_until_complete(get_session_history(session_id))
        if not history:
            return "No conversation history found for this session."
        lines = []
        for m in history[-10:]:  # last 10 messages
            lines.append(f"[{m['role'].upper()}]: {m['content'][:200]}")
        return "\n".join(lines)
    except Exception as exc:
        return f"Memory read failed: {exc}"


@tool
def memory_write(content: str) -> str:
    """
    Write a note or insight to memory for later recall.
    Input: JSON with 'session_id' and 'note'.
    Output: confirmation.
    """
    # This is a lightweight tool — actual session writes happen in routes
    try:
        data = json.loads(content)
        return f"Note saved to memory: {data.get('note', '')[:100]}"
    except Exception:
        return "Note acknowledged."


# ──────────────────────────────────────────────
# Tool registry
# ──────────────────────────────────────────────

ALL_TOOLS = [
    web_search,
    wikipedia_search,
    generate_podcast_script,
    summarize_content,
    format_podcast_structure,
    memory_read,
    memory_write,
]
